#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -f PyFoamS*
rm -f PyFoamH*
rm -rf Gnuplotting.analyzed
touch foam.foam
#rm -f constant/polyMesh/boundary > /dev/null 2>&1

#------------------------------------------------------------------------------
