#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
#. $WM_PROJECT_DIR/bin/tools/RunFunctions

blockMesh
decomposePar
pyFoamPlotRunner.py mpirun -np 4 rhoPimpleFoam -parallel | tee simu.log
#pyFoamPlotRunner.py rhoPimpleFoam
reconstructPar
